---   
- name: Destroy Elastic Load Balancer 
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/elb.yml
  roles:
    - remove_elb

- name: Terminate existing EC2 instances
  hosts: webserver1,webserver2,database
  vars_files:
    - vars/common.yml
  roles:
    - terminate_ec2
