- name: Provision WebServer1 EC2 instance
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/webserver1.yml
  roles:
    - ec2_create

- name: Provision WebServer2 EC2 instance
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/webserver2.yml
  roles:
    - ec2_create

- name: Provision Database EC2 instance
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/database.yml
  roles:
    - ec2_create
