- name: Destroy Elastic Load Balancer 
  hosts: localhost
  vars_files:
    - vars/common.yml
    - vars/elb.yml
  roles:
    - elb_remove

- name: Terminate existing EC2 instances
  hosts: webserver1,webserver2,database
  vars_files:
    - vars/common.yml
  roles:
    - ec2_terminate
