- name: Install all required dependencies
  yum: name={{ item }} state=installed
  with_items:
    - python
    - python-setuptools
    - python-devel
    - glibc-devel
    - gcc
    - patch
    - python-pip
    - MySQL-python
    - gcc-c++
    - libxml2-python
    - libxml2-devel
