---
- name: Create Elastic Load Balancer
  local_action:
    module: ec2_elb_lb
    state: present
    name: "{{ elb_name }}"
    security_group_ids: "{{ security_groups }}"
    instance_ids: "{{ hostvars[item].ec2_id }}"
    region: "{{ region }}"
    subnets: "{{ subnets }}"
    tags: "{{ elb_tags }}"
    purge_subnets: yes
    wait: yes
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 5000
    health_check:
      ping_protocol: http
      ping_port: 5000/
      response_timeout: 5
      interval: 10
      unhealthy_threshold: 4
      healthy_threshold: 2
  register: result
  with_items:
    - webserver1
    - webserver2
