- name: Install Python Flask dependency
  pip: 
    name: '{{ item }}'
    state: present
  with_items:
    - flask
    - flask-mysql

- name: Copy source code
  copy:
    src: "{{ role_path }}/files/app.py"
    dest: /opt/app.py

- name: Change file permissions
  file:
    path: /opt/app.py
    mode: 0764

- name: Start Web Server
  shell: python /opt/app.py
  environment:
    MYSQL_DATABASE_HOST: "{{ hostvars['database'].ec2_ip_address }}"